origin: husamemadh/hi


# Define what permissions can be granted
statements:
  - subjects:
      - 'repo:husamemadH@176228199/hi@1335106094:**' # any workflow from any branch
    permissions:
      contents: write  # Allow pushing
      pull-requests: write # Allow creating pull requests
